---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: true

platforms:
- name: freebsd-9.2
- name: freebsd-9.2-i386
- name: freebsd-10.0

suites:
- name: portsnap
  run_list:
  - recipe[freebsd::portsnap]
